### ISSUE TITLE
[Win32]t/TestInlineSetup.pm unworkable on Windows.

### ISSUE THREAD

**Issue by sisyphus** [ingydotnet/inline-c-pm#19]
Hi,
The Inline-C-0.62 test suite produces lots of warnings like:

cannot unlink file for C:\sisyphusion\Inline-C-0.62_Inline_01syntax.508\lib\auto_01syntax_t_05dd_01syntax_t_05dd.dll: Permission denied at t/TestInlineSetup.pm line 35.

(For the full scale of these and ensuing warnings see, for example:

http://www.cpantesters.org/cpan/report/d5d76ac2-97ed-1014-92c7-6d122b825c07

The problem is that the specified dll is still in use - and Windows will not allow that file to be removed while it's still in use. In pondering what to do about this, I came upon a couple of questions for which I have no answer.

1) Why do we want to create and destroy the build dir every time a test script is run ?
2) Why do we give these build dirs names that are probably (but not inevitably) unique ? Given that there's a good reason (which I'm not seeing) that these build dirs ought to be created and destroyed, why not just give them the same name ?

Cheers,
Rob

**Comment by mohawk2** [comment]
If #32 is fixed, so is this.
