### ISSUE TITLE
Makefile.PL needs non-core module

### ISSUE THREAD

**Issue by sisyphus** [ingydotnet/inline-c-pm#24]
The 0.62_03 Makefile.PL wants to load File::ShareDir::Install - but there's no guarantee that the module will be present.
If File::ShareDir::Install has not previously been installed, then the Makefile.PL simply aborts:

Can't locate File/ShareDir/Install.pm in @INC .... at Makefile.PL line 10

(When this happens on a smoker, no test report is generated.)

Neatest solution I can think of is to have Inline's Makefile.PL specify File::ShareDir::Install as a prerequisite - though, of course, strictly speaking that module is _not_ a prerequisite for Inline.

Is there a preferable way of dealing with this ?

Cheers,
Rob

**Comment by mohawk2** [comment]
Using a `share` dir is reasonable. Relying on `CONFIGURE_REQUIRES` being available is reasonable, since all modern CPAN clients know about it or can work around its absence. Closing.
