### ISSUE TITLE
ellipsis syntax doesn't bind with default parser (0.62_03)

### ISSUE THREAD

**Issue by sisyphus** [ingydotnet/inline-c-pm#25]
With 0.62_03 this script:

use warnings;
use strict;

use Inline C => <<'EOC';

void foo(SV \* x, ...) {
 dXSARGS;
 int i;

 for(i = 0; i < items; ++i) printf("hello\n");
}

EOC

foo(1, 2, 3);

Outputs:
Undefined subroutine &main::foo called at try.pl line 15.

Works fine if either ParseRecDescent or ParseRegExp are used.

**Comment by perlpunk** [comment]
This seems to be fixed, I just tested it.
Closing, please reopen if necessary.
