### ISSUE TITLE
old versions

### ISSUE THREAD

**Issue by chorny** [ingydotnet/inline-c-pm#35]
Please remove ETJ/Inline-C-0.62.tar.gz (and possibly earlier) from CPAN. This version is still indexed (probably because in newer versions some module was removed) and is tested by cpantesters smokers causing problems because it hangs.
CPAN mirrors disk space will be freed too.
In case removing is not possible, a new version can be released with empty modules that were removed in older versions.
You can check for other indexed old versions here: http://cpanold.chorny.net/

**Comment by mohawk2** [comment]
They now all say "Scheduled for deletion (due at Wed, 07 Jan 2015 11:09:36 GMT)".
