### ISSUE TITLE
Failed to install via cpanm

### ISSUE THREAD

**Issue by leetom** [ingydotnet/inline-c-pm#41]
I just tried to install Inline::C with cpanm (Perl 5.20.2) but failed.

Here is the error:

        323 #
	324 # chmod 755 blib/arch/auto/Math/Simple/Simple.bundle
	325 # /Users/leetom/perl5/perlbrew/perls/perl-5.20.2/bin/perl -MExtUtils::Command::MM -e 'cp_nonempty' -- Simple.bs blib/arch/auto/Math/Simple/Simple.bs 644
	326 #   Finished "make" Stage
	327 #
	328 #   Starting "make install" Stage
	329 # Running Mkbootstrap for Math::Simple ()
	330 # chmod 644 Simple.bs
	331 # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	332 # ERROR: Can't create '/'
	333 # Do not have write permissions on '/'
	334 # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	335 #  at -e line 1.
	336 # make[2]: *** [pure_site_install] Error 13
	337 #
	338 # A problem was encountered while attempting to compile and install your Inline

**Comment by mohawk2** [comment]
Could you get the Makefile it generates for the above test, and gist it to here?

**Comment by wbraswell** [comment]
@mohawk2 

build.log
http://pastebin.com/D4SUCanJ

Makefile.PL
http://pastebin.com/e30kJNcu

Makefile
http://pastebin.com/0QyPHXnc

Please let me know what else I can do to help fix this ASAP, it is totally broken, thanks!

**Comment by daoswald** [comment]
This could be related to HARNESS_OPTIONS=jn (where n is a number).  Inline::C has never been compatible with parallel testing in the test harness.  When I unset HARNESS_OPTIONS I get a clean install on ubuntu 15.04 with Perl 5.22.

**Comment by wbraswell** [comment]
I do not have HARNESS_OPTIONS set as an environmental variable, and it does not appear in my code anywhere, and I have never used it myself in the past.  So in my case, I do not believe HARNESS_OPTIONS is the culprit...  Unless it is getting called by some other dependency of Inline::C somehow without my knowledge?

**Comment by mohawk2** [comment]
@daoswald Some work did take place to make Inline::C test in parallel and I think at the time it worked. A test of the current (0.75) fails for me with `HARNESS_OPTIONS=j4` but succeeds with it unset, so now it does not.

@wbraswell are you the same person as @leetom ? I wasn't asking for the Makefile\* for Inline::C, but the ones generated for the individual test that is failing. Please provide those.

**Comment by leetom** [comment]
@mohawk2 
Sorry for the late reply.

https://gist.github.com/leetom/664bec009d459814b320

Here is the Makefile, and the environment is MacOS 10.10.3, Perl 5.20.2 (installed with perlbrew, default options).

Thank you!

**Comment by wbraswell** [comment]
@mohawk2 
No I am not leetom.

~/.cpanm/work/1434149286.7204/Inline-C-0.75/example/modules/Math-Simple-1.23/Makefile.PL
http://pastebin.com/GFb2njZD

~/.cpanm/work/1434149286.7204/Inline-C-0.75/example/modules/Boo-2.01/Makefile.PL
http://pastebin.com/n6ViQU0B

Are those the Makefiles you wanted?

**Comment by wbraswell** [comment]
Any progress here?

**Comment by mohawk2** [comment]
@wbraswell You do know you're allowed to look at and submit fixes for this yourself, right?

**Comment by mohawk2** [comment]
@leetom Evidently I was unclear, sorry about that. I don't need the Makefile for Inline::C, which you have supplied. I need the Makefile the relevant test generated as part of its build.

By the way, I note you have EUMM 6.98. Inline::C now requires 7.0+ to test successfully. I see Inline::C's metadata says it needs that to run, but not to test, which is an omission. Could you upgrade your EUMM to latest and see if this still occurs?

**Comment by wbraswell** [comment]
@mohawk2 
I've asked you two questions, can you please answer at least the first one?

**Comment by leetom** [comment]
@mohawk2  Problem solved after I update MakeMaker to 7.04. Thank you very much!

**Comment by wbraswell** [comment]
I can confirm this issue is solved by upgrading from ExtUtils::MakeMaker v6.66 to v7.04, this was a little tricky for me because cpanm and local::lib correctly installed v7.04 in ~/perl5 but the old v6.66 was still installed system-wide, so I had to delete ~/perl5 and use cpan (not cpanm) to install v7.04 system-wide.

I believe this issue can be closed.

**Comment by mohawk2** [comment]
@leetom You're welcome!
