### ISSUE TITLE
New recipe for the Inline::C Cookbook

### ISSUE THREAD

**Issue by rongrw** [ingydotnet/inline-c-pm#56]
Hi all,

Following a recent discussion on the Inline mailing list about accessing Perl variables directly from a C function, I've put together some sample code that I think would be appropriate to add into the Inline::C Cookbook. I've attached a file in plain text format that contains the full recipe.

Would it be possible to add this new recipe into the Cookbook, perhaps under the "Meat & Potatoes" chapter?

Kind Regards,
Ron.

[C-Cookbook-entry.txt](https://github.com/ingydotnet/inline-c-pm/files/659138/C-Cookbook-entry.txt)

**Comment by mohawk2** [comment]
Hi Ron, this will probably be easier for the maintainers to process if you actually make a pull request with this?

**Comment by wbraswell** [comment]
@rongrw 
Good job on the new cookbook entry!  :+1: 
I agree with @mohawk2, you should make a pull request.

**Comment by rongrw** [comment]
I've noticed that the Cookbook is in (.swim) format in the master branch. Sorry for asking these simple questions, but what is the (.swim) format and how do I convert it to (.pod) to ensure the formatting looks correct?

I'm assuming that I would have to add my new recipe into Cookbook.swim in order to create a pull request.

Thank you.

**Comment by mohawk2** [comment]
That's a great question! As I recall, you have to install `Zilla::Dist` and do (I think) `zild dist` to make a `.pm` file you could inspect.

If that proves troublesome, then just a best guess at the formatting (since the markup is very easy to cargo-cult from other sections) and a PR is still much easier to deal with.

**Comment by rongrw** [comment]
Thanks for the suggestion @mohawk2 

Another option is to install the Swim module. This module comes with a utility program called "swim" which can convert (.swim) format to (.pod) format as well as other formats. So, in my case, I use the following command:

`swim --to=pod Cookbook.swim > Cookbook.pod`

**Comment by wbraswell** [comment]
@rongrw 
As part of your documentation update, can you please include the above info (at least) about the Swim module?

**Comment by rongrw** [comment]
Hi @wbraswell ,

OK, that's fine. Do you think Swim together with the above command should be mentioned in an Appendix in the Cookbook?

**Comment by daoswald** [comment]
Is there not a CONTRIBUTING doc attached to the repo? That's where mention
of swim would belong.

**Comment by wbraswell** [comment]
@rongrw 
There is not currently a CONTRIBUTING doc, but per @daoswald 's recommendation, you should go ahead and create one to contain your swim info.

**Comment by rongrw** [comment]
I have now finished my updates to Cookbook.swim. Also, I'm happy to write up a CONTRIBUTING file as suggested by @daoswald . I'll use Inline's version of this file as a guide.

Thanks for all your suggestions.

**Comment by rongrw** [comment]
I've now completed the CONTRIBUTING file. As I'm a little unsure with what I've written for this file, I've attached it to this post. If you could have a look at it that would be great. Let me know if it needs any further amendments or additions. Thank you.

[CONTRIBUTING.txt](https://github.com/ingydotnet/inline-c-pm/files/733900/CONTRIBUTING.txt)

**Comment by wbraswell** [comment]
@rongrw 
Please add info about the IRC chat room to your CONTRIBUTING.txt file
server: irc.perl.org
channel: #inline

**Comment by rongrw** [comment]
Thank you @wbraswell for your suggestion.

I've added a section titled "IRC Chat Room" to the CONTRIBUTING file. I've also created a pull request now for updating the C-Cookbook.

**Comment by perlpunk** [comment]
i think this can be closed since the PR was applied

**Comment by rongrw** [comment]
@perlpunk , yes, it's fine to close this issue. Regarding having a CONTRIBUTING file in the repo, do you want me to create a new issue for this? Since I wrote this file back in Jan, I'm happy to do that.
Thank you.

**Comment by perlpunk** [comment]
@rongrw yeah, that's probably a good idea.
Since Dist::Zilla is already generating a generic CONTRIBUTING file for CPAN, it shouldn't be a problem to put that file into the repo, along with distribution specific advice.
I'll try to talk to @ingydotnet later

**Comment by rongrw** [comment]
OK @perlpunk that's fine. We can use the generated CONTRIBUTING file - I'll then add a section on Swim since it's not obvious how to edit the Inline::C Cookbook file.
