### ISSUE TITLE
Tests fail on Strawberry Perl 5.24.1.1 (64bit) Windows 10 due to missing rm/diff

### ISSUE THREAD

**Issue by jfroebe** [ingydotnet/inline-c-pm#60]
Platform: Strawberry Perl 5.24.1.1 (64bit) Windows 10
Inline::C version: 0.76

Test t/parse-pegex.t is looking for platform specific rm and diff.  These should be replaced with perl implementations.

[inline-c_testfailures.txt](https://github.com/ingydotnet/inline-c-pm/files/900251/inline-c_testfailures.txt)

**Comment by nanis** [comment]
Same issue with Visual Studio 2013 compiled `perl` 5.24.1 on Windows 10. At the very least, tests should be skipped if external programs are not found:

```text
t\parse-pegex.t .......... 9/? 'diff' is not recognized as an internal or external command,
operable program or batch file.
'diff' is not recognized as an internal or external command,
....
diff' is not recognized as an internal or external command,
operable program or batch file.
```

### Workaround
Visual Studio optionally offers to install Git which installs some useful utilities (including `perl`) in `c:\Program Files\git\usr\bin` which is not usually added to `%PATH%`. Appending that directory to the path:

```text
path=%path%;"c:\Program Files\git\usr\bin"
```

results in a bunch more failures as in
```
$ prove -vb t\parse-pegex.t
Test Summary Report
-------------------
t\parse-pegex.t (Wstat: 0 Tests: 24 Failed: 0)
  TODO passed:   4, 7-9
Files=1, Tests=24,  3 wallclock secs ( 0.11 usr +  0.02 sys =  0.13 CPU)
Result: PASS
```

**Comment by perlpunk** [comment]
thanks, i created PR #66

**Comment by perlpunk** [comment]
@nanis @jfroebe we just released Inline::C 0.78, could you test if it works now?

**Comment by nanis** [comment]
```text
C:\...\Temp> cpanm Inline::C
...
Building and testing Inline-C-0.78 ... OK
Successfully installed Inline-C-0.78
```

Thank you very much and apologies for the late response.

**Comment by perlpunk** [comment]
cool, thanks!
