### ISSUE TITLE
t/32include_dirs_double_quotes_bad.t failures (with clang and older gcc?)

### ISSUE THREAD

**Issue by eserte** [ingydotnet/inline-c-pm#79]
t/32include_dirs_double_quotes_bad.t in 0.79_001 fails on some systems. It seems that FreeBSD 10 .. 12 is affected (where clang is the default C compiler) and older Linux and FreeBSD systems (CentOS 6, Debian/wheezy, FreeBSD 9) --- maybe because an older gcc is installed here.

Sample fail reports:
* http://www.cpantesters.org/cpan/report/63929eb0-1e7a-11e9-83e1-d7b49caa1f57
* http://www.cpantesters.org/cpan/report/8f87b680-1e12-11e9-9fb5-f9dfb1e56781

**Comment by perlpunk** [comment]
Yep, thanks, people are working on it. I just released 0.79_002

**Comment by eserte** [comment]
0.79_002 looks better. Now it fails only on Debian/wheezy. Sample report: http://www.cpantesters.org/cpan/report/fb8dcd46-216f-11e9-88ff-a1e627951fcb

**Comment by wbraswell** [comment]
This should be fixed by https://github.com/ingydotnet/inline-c-pm/pull/80
@sisyphus or @perlpunk Please merge pull request, to be included in next CPAN dev release.

**Comment by mohawk2** [comment]
If #72 tracks, could this now be closed?

**Comment by wbraswell** [comment]
Yes, this is a sub-issue of #72 and can thus be closed to avoid redundancy.
@eserte please follow issue #72 for updates.
