### ISSUE TITLE
Config directives are no longer cumulative

### ISSUE THREAD

**Issue by sisyphus** [ingydotnet/inline-c-pm#82]
As discovered in the course of issue #78, separate config directives are no longer cumulative, though I know they once were - and the Inline documentation states clearly that specified "Config options are inherited and additive".
So, for example with this script:

use Inline C => Config => FORCE_BUILD => 1;
use Inline C => Config => BUILD_NOISY => 1;
use Inline C => <<'EOC';
void foo() {
  printf("hello world");
}

EOC

foo();
__END__

I get a noisy build, but the force_build directive is ignored, and ensuing runs of the script skip don't perform the re-compilation.

If I reverse the order of the 2 "Config" directives, the script re-compiles every time I run it, but does so silently.

At this stage I haven't determined whether the offending code is in the Inline::C module or the Inline module.

Cheers,
Rob

**Comment by sisyphus** [comment]
Sorry - should have added that this is using latest Inline (0.80), Inline::C (0.78) and Pegex (0.70).

**Comment by mohawk2** [comment]
Having fixed this in https://github.com/ingydotnet/inline-pm/pull/71, I'm fairly sure it never did accumulate for per-language.

**Comment by perlpunk** [comment]
fixed by https://github.com/ingydotnet/inline-pm/pull/71
