### ISSUE TITLE
Can't call libcurl with Inline::C on Windows

### ISSUE THREAD

**Issue by xiaoyafeng** [ingydotnet/inline-c-pm#95]
please reference here [https://www.perlmonks.org/?node_id=11108859](url)
I suspect Inline::C can't tell dll.a file correctly.  Is there a way to know why dynaloader can't call xs.dll file?

**Comment by sisyphus** [comment]
AFAICT, if both libcurl.dll.a (import library) and libcurl.a (static library) exist in the same folder, then "-lcurl" will link to libcurl.a.
If one wants to link to libcurl.dll.a then one has to either:
a) remove or rename libcurl.a
or
b) link by specifying "-lcurl.dll"

I think this behaviour is controlled by gcc's linker, and has nothing to do with Inline::C.

Cheers,
Rob

**Comment by xiaoyafeng** [comment]
Hi Rob,
            When I explicitly use -lcurl.dll.a, linker will sucessfully get thing done, but Dynaloader throw an error:
Finished Build Compile Stage

Had problems bootstrapping Inline module 'bb_pl_d714'

Can't load 'C:\Users\Administrator\Downloads\curl-7.67.0_4-win64-mingw\curl-7.67.0-win64-mingw\_Inline\lib/auto/bb_pl_d714/bb_pl_d714.xs.dll' for
module bb_pl_d714: load_file:The specified module could not be found at C:/perl/perl/lib/DynaLoader.pm line 193.
  at C:/perl/perl/site/lib/Inline.pm line 541.


 at bb.pl line 6.
BEGIN failed--compilation aborted at bb.pl line 6.

**Comment by xiaoyafeng** [comment]
Thanks Rob,  If I use pure portable strawberry perl, it's still failed even if I add bin into PATH. but if I use libcurl in MSYS2 , it goes fine.  Since Idon't want to deploy both MSYS2 and strawberry perl, I'll try copy libcurl to strawberryperl directory.
